version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: veromanich/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: veromanich/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: veromanich/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media:/media
    depends_on:
      - backend
      - frontend
